"""empty message

Revision ID: 6c3764a96206
Revises: fd5865c3be3b
Create Date: 2022-08-18 21:05:15.271310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c3764a96206'
down_revision = 'fd5865c3be3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=False))
    op.drop_column('venue', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    op.alter_column('shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
