"""empty message

Revision ID: fd5865c3be3b
Revises: 83effdcecca3
Create Date: 2022-08-17 15:11:00.111885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5865c3be3b'
down_revision = '83effdcecca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'show_date')
    # ### end Alembic commands ###
